### ISSUE TITLE
自己压缩的话，一直报错，望解答

### ISSUE THREAD

**Issue by struggling-bird** [ecomfe/echarts-optimizer#16]
/usr/local/lib/node_modules/echarts-optimizer/index.js:131
        result += analyse.getAnalysed(mod).builtCode;
                                          ^
TypeError: Cannot read property 'builtCode' of undefined
    at /usr/local/lib/node_modules/echarts-optimizer/index.js:131:43
    at Array.forEach (native)
    at Object.exports.packAsAll (/usr/local/lib/node_modules/echarts-optimizer/index.js:130:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/echarts-optimizer/bin/echarts-optimize:33:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)

**Comment by errorrik** [comment]
我这没发现问题，你用的zrender和echarts版本号是啥，是否正确配置了zrender和echarts的源码目录？

**Comment by struggling-bird** [comment]
着实汗颜。。。我目录没搞对。。。可以了＝＝、谢大神

**Comment by errorrik** [comment]
搞定就行。close了
